### ISSUE TITLE
Swift proposal SE-0345 not implemented in version 0.50700.1 (Xcode 14)

### ISSUE THREAD

**Issue by mihaicris-adoreme** [apple/swift-format#448] opened 2022-11-08 14:25 UTC
Swift proposal SE-0345 (Implemented in Swift 5.7 Xcode 14)
is not implemented in swift-format version 0.50700.1 (Xcode 14)
All usages generate an error: file contains invalid or unrecognized Swift syntax.

https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md

**Comment by kkk669** [comment] 2022-11-08 14:30
It should have been fixed by #409.

**Comment by allevato** [comment] 2022-11-08 15:27
Do you have a reduced example that doesn't work, and can you verify that you're using 0.50700.1?

**Comment by mihaicris-adoreme** [comment] 2022-11-08 15:28
I can provide some examples, but if I replace the construction `if let value` with `if let value = value` the file is formated with success otherwise it fails indicating the line number with the if let or guard let declaration.

**Comment by ali-hk** [comment] 2023-01-15 20:31
I'm encountering the same issue on 0.50700.1
with the following minimal code:
```swift
return try await withCheckedThrowingContinuation { [weak self] continuation in
    guard let self else {
          return
    }
}
```

replacing the `guard let self else {` with `guard let self = self else {` resolves the following error:
`error: file contains invalid or unrecognized Swift syntax.`

The issue is not specific to guard let, as the following minimal code also produces the error:
```swift
func someFunc(someVar: Int?) {
    if let someVar {
    }
}
```

**Comment by Vaberer** [comment] 2023-01-31 14:21
Can you update brew to 0.50700.1 ?

**Comment by mihaicris-adoreme** [comment] 2023-02-03 08:24
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/swift-format.rb

Brew formula points to 3dd9b517b9e9846435aa782d769ef5825e7c2d65  tag  0.50700.0

Maybe this is the issue?

**Closed** 2023-08-15 15:11 UTC
