### ISSUE TITLE
Split comments if they exceed the line limit

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-format#723] opened 2024-04-24 05:41 UTC
Formatting the following leaves the line comment as a single line even though it exceeds the line limit. We should break it up into multiple lines.

```swift
// some very long comment that just goes on and on and one without providing any real value but it reaches past the end of the line limit
```

Other interesting cases to consider are

#### End of line comments

I’m honestly not sure how to break this best, would make sense to check what eg. `clang-format` does
```swift
print("Hello, world!")  // some very long comment that just goes on and on and one without providing any real value but it reaches past the line limit
```

#### Indented comment parts

Here we should probably wrap the comment at the same indentation level that the line already has (ie. the wrapped line should also have 3 spaces after `//`)

```swift
// - some very long comment in a markdown list 
//   that just goes on and on and one without providing any real value but it reaches past line limit
```

Here, the wrapped line should also be aligned with `some`, not entirely sure what the general rule should be.

```swift
// - some very long comment in a markdown list that just goes on and on and one without providing any real value but it reaches past the line limit
```

**Comment by ahoppen** [comment] 2024-04-24 06:03
Synced to Apple’s issue tracker as rdar://126967198

**Comment by allevato** [comment] 2024-04-24 12:01
Duplicate of https://github.com/apple/swift-format/issues/469?

**Closed** 2024-04-24 17:50 UTC
